wandb_version: 1

tutorial:
  desc: null
  value: 'True'
learning_rate:
  desc: null
  value: 0.0005
gamma:
  desc: null
  value: 0.99
gae:
  desc: null
  value: 1.0
value_coef:
  desc: null
  value: 0.5
entropy_coef:
  desc: null
  value: 0.01
clip_grad_norm:
  desc: null
  value: 0.5
seed:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1702232814.561723
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
