wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: A2C
env:
  desc: null
  value: HalfCheetah-v4
episodes:
  desc: null
  value: 2000
gamma:
  desc: null
  value: 0.99
hid_layer:
  desc: null
  value: 512
hid_layer2:
  desc: null
  value: 1024
hid_layer3:
  desc: null
  value: 512
entropy_beta:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1702227892.717541
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
